'use client';

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from '@react-pdf/renderer';
import { type Proposal } from '@/lib/types';

// Register fonts
Font.register({
  family: 'Inter',
  src: 'https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hiA.woff2',
});

const styles = StyleSheet.create({
  page: {
    backgroundColor: '#FFFFFF',
    padding: 48,
    fontFamily: 'Inter',
  },
  header: {
    marginBottom: 32,
    paddingBottom: 16,
    borderBottom: '2px solid #F97316',
  },
  brandName: {
    fontSize: 10,
    color: '#F97316',
    letterSpacing: 2,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  headline: {
    fontSize: 22,
    color: '#09090B',
    lineHeight: 1.4,
    fontWeight: 700,
    marginBottom: 12,
  },
  hook: {
    fontSize: 11,
    color: '#3F3F46',
    lineHeight: 1.6,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 10,
    color: '#F97316',
    letterSpacing: 2,
    marginBottom: 8,
    textTransform: 'uppercase',
    fontWeight: 700,
  },
  sectionContent: {
    fontSize: 11,
    color: '#3F3F46',
    lineHeight: 1.6,
  },
  scopeItem: {
    fontSize: 11,
    color: '#3F3F46',
    marginBottom: 4,
    paddingLeft: 12,
  },
  bullet: {
    color: '#F97316',
  },
  investmentBox: {
    backgroundColor: '#FFF7ED',
    border: '1px solid #FDBA74',
    borderRadius: 8,
    padding: 12,
    marginBottom: 24,
  },
  investmentNote: {
    fontSize: 10,
    color: '#9A3412',
    marginBottom: 4,
    fontStyle: 'italic',
  },
  investmentRange: {
    fontSize: 14,
    color: '#09090B',
    fontWeight: 700,
  },
  ctaBox: {
    backgroundColor: '#09090B',
    borderRadius: 8,
    padding: 14,
    marginBottom: 16,
  },
  ctaText: {
    fontSize: 12,
    color: '#FFFFFF',
    textAlign: 'center',
  },
  psLine: {
    fontSize: 10,
    color: '#71717A',
    fontStyle: 'italic',
    marginTop: 8,
  },
  twoCol: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  col: {
    flex: 1,
    backgroundColor: '#F4F4F5',
    borderRadius: 6,
    padding: 10,
  },
  colLabel: {
    fontSize: 9,
    color: '#71717A',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  colValue: {
    fontSize: 11,
    color: '#18181B',
  },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 48,
    right: 48,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTop: '1px solid #E4E4E7',
    paddingTop: 8,
  },
  footerText: {
    fontSize: 9,
    color: '#A1A1AA',
  },
});

interface ProposalDocumentProps {
  proposal: Proposal;
}

export function ProposalDocument({ proposal }: ProposalDocumentProps) {
  const p = proposal.proposal_content!;
  const disc = proposal.disc_profile;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.brandName}>Generated by Closr</Text>
          <Text style={styles.headline}>{p.headline}</Text>
          <Text style={styles.hook}>{p.hook}</Text>
        </View>

        {/* Problem */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{p.problem_section.title}</Text>
          <Text style={styles.sectionContent}>{p.problem_section.content}</Text>
        </View>

        {/* Solution */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{p.solution_section.title}</Text>
          <Text style={styles.sectionContent}>{p.solution_section.content}</Text>
        </View>

        {/* Scope */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{p.scope_section.title}</Text>
          {p.scope_section.items.map((item, i) => (
            <Text key={i} style={styles.scopeItem}>
              → {item}
            </Text>
          ))}
        </View>

        {/* Timeline + Investment */}
        <View style={styles.twoCol}>
          <View style={styles.col}>
            <Text style={styles.colLabel}>Timeline</Text>
            <Text style={styles.colValue}>{p.timeline}</Text>
          </View>
          <View style={styles.col}>
            <Text style={styles.colLabel}>DISC Profile</Text>
            <Text style={styles.colValue}>
              {disc ? `${disc.disc_type} – ${disc.disc_label}` : 'Not analyzed'}
            </Text>
          </View>
        </View>

        {/* Investment */}
        <View style={styles.investmentBox}>
          <Text style={styles.investmentNote}>{p.investment.note}</Text>
          <Text style={styles.investmentRange}>{p.investment.range}</Text>
        </View>

        {/* CTA */}
        <View style={styles.ctaBox}>
          <Text style={styles.ctaText}>{p.cta}</Text>
        </View>

        {/* PS */}
        <Text style={styles.psLine}>{p.ps_line}</Text>

        {/* Footer */}
        <View style={styles.footer}>
          <Text style={styles.footerText}>
            Prepared for: {proposal.prospect_name || 'Prospect'}
          </Text>
          <Text style={styles.footerText}>
            {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
          </Text>
        </View>
      </Page>
    </Document>
  );
}
