import { Navbar } from '@/components/shared/Navbar';
import { Footer } from '@/components/shared/Footer';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy — Closr',
  description: 'Privacy Policy for Closr, the AI-powered proposal and cold email generation platform.',
};

const LAST_UPDATED = 'March 15, 2026';
const CONTACT_EMAIL = 'privacy@closr.io';
const COMPANY = 'Closr';
const WEBSITE = 'closr-sand.vercel.app';

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#09090B]">
      <Navbar />
      <main className="pt-32 pb-24">
        <div className="max-w-3xl mx-auto px-4 sm:px-6">

          {/* Header */}
          <div className="mb-12">
            <p className="text-sm font-medium text-[#F97316] mb-3 uppercase tracking-wider">Legal</p>
            <h1 className="font-serif text-4xl sm:text-5xl text-[#FAFAFA] mb-4">Privacy Policy</h1>
            <p className="text-[#71717A] text-sm">Last updated: {LAST_UPDATED}</p>
          </div>

          <div className="space-y-10 text-[#A1A1AA] leading-relaxed">

            <Section title="1. Introduction">
              <p>
                {COMPANY} (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) operates the website at {WEBSITE} and related services (the &quot;Service&quot;). This Privacy Policy explains how we collect, use, disclose, and protect your information when you use the Service. By using the Service, you agree to the collection and use of information as described in this policy.
              </p>
              <p>
                We take your privacy seriously. We collect only what we need, use it only to provide the Service, and do not sell your personal data to third parties.
              </p>
            </Section>

            <Section title="2. Information We Collect">
              <p>We collect the following categories of information:</p>
              <SubSection title="Account Information">
                <p>When you create an account, we collect your <strong className="text-[#FAFAFA]">email address</strong> and optionally your <strong className="text-[#FAFAFA]">name</strong>. This is used to identify your account, send authentication emails, and communicate service updates.</p>
              </SubSection>
              <SubSection title="Prospect Input Data">
                <p>When you use the proposal generation feature, you provide text describing your prospect (e.g., LinkedIn bio, job description, communication style). This <strong className="text-[#FAFAFA]">prospect text</strong> is used solely to generate your proposal and is stored in your account so you can access your proposal history.</p>
              </SubSection>
              <SubSection title="Generated Content">
                <p>Proposals and emails generated by the Service are stored in your account so you can access, edit, and export them at any time.</p>
              </SubSection>
              <SubSection title="Usage Data">
                <p>We automatically collect basic usage information such as pages visited, features used, and proposal generation counts. This is used to enforce plan limits and improve the Service.</p>
              </SubSection>
              <SubSection title="Payment Information">
                <p>We do not store your payment card details. All payment information is handled directly by <strong className="text-[#FAFAFA]">Paddle</strong>, our payment processor. We receive only a customer ID and subscription status from Paddle.</p>
              </SubSection>
            </Section>

            <Section title="3. How We Use Your Information">
              <p>We use the information we collect to:</p>
              <ul>
                <li>Create and manage your account.</li>
                <li>Send authentication emails (magic links) to log you in.</li>
                <li>Process prospect text through the OpenAI API to generate proposals and emails.</li>
                <li>Store your proposals so you can access your history.</li>
                <li>Enforce plan-level usage limits (e.g., proposal counts).</li>
                <li>Process your subscription payments through Paddle.</li>
                <li>Send transactional emails (billing receipts, service notices).</li>
                <li>Improve and debug the Service through aggregate, anonymized usage analytics.</li>
                <li>Comply with legal obligations.</li>
              </ul>
              <p>We do not use your data for advertising purposes. We do not sell, rent, or trade your personal data.</p>
            </Section>

            <Section title="4. Third-Party Services">
              <p>The Service uses the following third-party providers. Each has their own privacy policy governing how they handle data:</p>

              <div className="space-y-4 mt-2">
                <ThirdParty
                  name="OpenAI"
                  purpose="AI processing — your prospect text and proposal context are sent to OpenAI's API to generate proposal and email content."
                  link="https://openai.com/policies/privacy-policy"
                />
                <ThirdParty
                  name="Supabase"
                  purpose="Database and authentication — your account information, proposals, and usage data are stored in Supabase's managed Postgres database. Authentication emails are sent via Supabase Auth."
                  link="https://supabase.com/privacy"
                />
                <ThirdParty
                  name="Paddle"
                  purpose="Payment processing — subscription billing, payment card processing, and VAT/tax handling. Paddle is the Merchant of Record for all transactions."
                  link="https://www.paddle.com/legal/privacy"
                />
                <ThirdParty
                  name="Vercel"
                  purpose="Hosting — the Service is hosted on Vercel's infrastructure. Request logs and edge network data may be processed by Vercel."
                  link="https://vercel.com/legal/privacy-policy"
                />
              </div>
            </Section>

            <Section title="5. Data Storage and Security">
              <p>
                Your data is stored in Supabase&apos;s managed PostgreSQL database with row-level security (RLS) policies enforced — meaning you can only access your own data. We use HTTPS/TLS encryption for all data in transit.
              </p>
              <p>
                While we implement industry-standard security measures, no method of electronic transmission or storage is 100% secure. We cannot guarantee absolute security of your data. In the event of a data breach, we will notify affected users as required by applicable law.
              </p>
            </Section>

            <Section title="6. Data Retention">
              <p>
                We retain your account information and proposals for as long as your account is active. If you delete your account, we will delete your personal data and proposals within 30 days, except where retention is required by law or for legitimate business purposes (such as fraud prevention or resolving disputes).
              </p>
              <p>
                Prospect text you input is retained as part of your proposal records until you delete the proposal or your account.
              </p>
            </Section>

            <Section title="7. Your Rights">
              <p>Depending on your location, you may have the following rights regarding your personal data:</p>
              <ul>
                <li><strong className="text-[#FAFAFA]">Access:</strong> Request a copy of the personal data we hold about you.</li>
                <li><strong className="text-[#FAFAFA]">Correction:</strong> Request correction of inaccurate or incomplete data.</li>
                <li><strong className="text-[#FAFAFA]">Deletion:</strong> Request deletion of your personal data. You can delete individual proposals from your dashboard. To delete your entire account and data, contact us at {CONTACT_EMAIL}.</li>
                <li><strong className="text-[#FAFAFA]">Portability:</strong> Request an export of your data in a structured, machine-readable format.</li>
                <li><strong className="text-[#FAFAFA]">Objection:</strong> Object to or restrict certain processing of your data.</li>
                <li><strong className="text-[#FAFAFA]">Withdraw consent:</strong> Where processing is based on consent, you may withdraw consent at any time.</li>
              </ul>
              <p>
                To exercise any of these rights, contact us at{' '}
                <a href={`mailto:${CONTACT_EMAIL}`} className="text-[#F97316] hover:underline">{CONTACT_EMAIL}</a>.
                We will respond within 30 days.
              </p>
            </Section>

            <Section title="8. Cookies">
              <p>
                The Service uses the following types of cookies and local storage:
              </p>
              <ul>
                <li><strong className="text-[#FAFAFA]">Authentication cookies:</strong> Set by Supabase Auth to keep you logged in. These are strictly necessary for the Service to function.</li>
                <li><strong className="text-[#FAFAFA]">Session storage:</strong> Temporary browser storage used to maintain your session state. Cleared when you close your browser.</li>
              </ul>
              <p>
                We do not use advertising cookies or third-party tracking cookies. You can control cookies through your browser settings, but disabling authentication cookies will prevent you from logging in.
              </p>
            </Section>

            <Section title="9. Children's Privacy">
              <p>
                The Service is not directed to children under the age of 16. We do not knowingly collect personal data from children under 16. If you believe we have inadvertently collected data from a child under 16, please contact us at {CONTACT_EMAIL} and we will delete it promptly.
              </p>
            </Section>

            <Section title="10. International Data Transfers">
              <p>
                {COMPANY} operates globally. Your data may be processed and stored in countries outside your own, including the United States, where data protection laws may differ from those in your country. By using the Service, you consent to such transfers. Where required, we implement appropriate safeguards such as Standard Contractual Clauses.
              </p>
            </Section>

            <Section title="11. Changes to This Policy">
              <p>
                We may update this Privacy Policy from time to time. We will notify you of material changes by posting the updated policy on the Service with a revised &quot;Last updated&quot; date and, where appropriate, by email. Continued use of the Service after the effective date of the updated policy constitutes acceptance.
              </p>
            </Section>

            <Section title="12. Contact">
              <p>
                If you have questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us:
              </p>
              <p>
                <strong className="text-[#FAFAFA]">{COMPANY} — Privacy</strong><br />
                Email: <a href={`mailto:${CONTACT_EMAIL}`} className="text-[#F97316] hover:underline">{CONTACT_EMAIL}</a><br />
                Website: <a href={`https://${WEBSITE}`} className="text-[#F97316] hover:underline">{WEBSITE}</a>
              </p>
            </Section>

          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-xl font-semibold text-[#FAFAFA] mb-4 pb-2 border-b border-[#27272A]">{title}</h2>
      <div className="space-y-3 text-[#A1A1AA] text-sm leading-7">
        {children}
      </div>
    </section>
  );
}

function SubSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h3 className="text-[#FAFAFA] font-medium text-sm mb-1">{title}</h3>
      <div className="text-[#A1A1AA] text-sm leading-7">{children}</div>
    </div>
  );
}

function ThirdParty({ name, purpose, link }: { name: string; purpose: string; link: string }) {
  return (
    <div className="bg-[#111113] border border-[#27272A] rounded-lg p-4">
      <div className="flex items-start gap-3">
        <div>
          <p className="text-[#FAFAFA] font-medium text-sm mb-1">{name}</p>
          <p className="text-[#A1A1AA] text-sm leading-relaxed">{purpose}</p>
          <a
            href={link}
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#F97316] text-xs hover:underline mt-1 inline-block"
          >
            View {name} Privacy Policy →
          </a>
        </div>
      </div>
    </div>
  );
}
